version: '2'

services:
  sdev:
    build:
      context: .
      args:
        SSH_USER_PASSWD: ${SSH_USER_PASSWD}
    container_name: sdev
    hostname: sdev
    restart: always
    ports:
      - ${SDEV_SSH_PORT}:22
    volumes:
      - ~/dev:/home/sshuser/dev

networks:
  default:
    name: dev_net